kind: pipeline
type: ssh
name: default

server:
  host: 
      from_secret: ssh_host
  username: 
      from_secret: ssh_username
  password:
    from_secret: ssh_password
 steps:
- name: greeting
  commands:
  - echo hello world
